Use bundler 2.2.0.rc.1
There's a bug in the `rake release` task that's fixed in the latest
bundler rc release and it's preventing me from releasing. I get this:

```
$ bin/rake release
activeadmin 2.8.1 built to pkg/activeadmin-2.8.1.gem.
Tagged v2.8.1.
Untagging v2.8.1 due to error.
rake aborted!
Couldn't git push. `git push  --tags' failed with the following output:

To https://github.com/activeadmin/activeadmin
 * [new tag]             v2.8.1 -> v2.8.1
 ! [rejected]            v2.7.0 -> v2.7.0 (already exists)
error: failed to push some refs to 'https://github.com/activeadmin/activeadmin'
hint: Updates were rejected because the tag already exists in the remote.
```

I think I could also fix it by messing with my local tags, but I'd like
to try the bundler rc release too.